(function(){'use strict';
const $=id=>document.getElementById(id),data=window.SLV_DEMO_FIELDS,answers={},files={},urls=[];
const categories=[...new Set(data.map(f=>f.category))];categories.splice(1,0,'HOME PLACEMENT ON YOUR LOT');const groups=categories.map(name=>({name,fields:data.filter(f=>f.category===name)}));let index=0;
const title=s=>s.toLowerCase().replace(/(^|\s)\S/g,c=>c.toUpperCase());
groups.forEach((g,i)=>{const o=document.createElement('option');o.value=i;o.textContent=title(g.name);$('sectionPicker').append(o)});
function field(f){const wrap=document.createElement('div');wrap.className='field';if(f.type==='submit'){const p=document.createElement('p');p.textContent='In the customer intake, this step submits the selected request. Continue to finish this demo without submitting.';wrap.append(p);return wrap}if(f.type==='instruction'){const p=document.createElement('p');p.textContent=f.label;wrap.append(p);return wrap}
const label=document.createElement('label');label.htmlFor=f.id;label.textContent=f.label;wrap.append(label);
if(f.type==='file'){const choices=document.createElement('div');choices.className='choices';const status=document.createElement('p');status.className='chosen';status.textContent=files[f.id]||'Optional practice selection. Files are not uploaded.';
[['Camera','image/*','environment'],['Library','image/*,video/*',''],['Files','','']].forEach(([name,accept,capture],i)=>{const l=document.createElement('label');l.className='file-choice';l.textContent=name;const input=document.createElement('input');input.type='file';input.id=i===0?f.id:f.id+'-'+i;input.setAttribute('aria-label',name+' for '+f.label);if(accept)input.accept=accept;if(capture)input.setAttribute('capture',capture);input.addEventListener('change',()=>{const file=input.files[0];if(!file)return;files[f.id]=file.name+' — selected locally only';status.textContent=files[f.id]});l.append(input);choices.append(l)});wrap.append(choices,status);return wrap}
let input=document.createElement(f.type==='dropdown'?'select':'input');input.id=f.id;input.autocomplete='off';if(f.type==='dropdown'){const blank=document.createElement('option');blank.textContent='Choose or skip';blank.value='';input.append(blank);f.options.split(',').forEach(s=>{const o=document.createElement('option');o.value=s.trim();o.textContent=s.trim();input.append(o)})}else input.type=['email','number','checkbox'].includes(f.type)?f.type:'text';if(input.type==='checkbox')input.checked=!!answers[f.id];else input.value=answers[f.id]||'';input.addEventListener('change',()=>answers[f.id]=input.type==='checkbox'?input.checked:input.value);wrap.append(input);return wrap}
function render(){const g=groups[index];$('sectionPicker').value=index;$('progress').textContent=(index+1)+' / '+groups.length;$('title').textContent=title(g.name);$('fields').replaceChildren();$('reference').replaceChildren();$('back').disabled=index===0;$('next').textContent=index===groups.length-1?'Finish demo':'Next →';$('sectionNote').textContent='All fields are optional in this demo. You can jump to any section.';
if(g.name==='HOME PLACEMENT ON YOUR LOT'){$('sectionNote').textContent='Sample placement only. The customer intake uses a live map; this demo uses an illustrative lot. Tap to place the front-door marker.';const plot=document.createElement('button');plot.className='plot';plot.setAttribute('aria-label','Sample lot: place front door');plot.textContent='SAMPLE LOT — TAP TO PLACE FRONT DOOR';const pin=document.createElement('span');pin.className='pin';pin.textContent='⌖';pin.style.left='50%';pin.style.top='50%';plot.append(pin);plot.onclick=e=>{const rect=plot.getBoundingClientRect();pin.style.left=(e.clientX?100*(e.clientX-rect.left)/rect.width:50)+'%';pin.style.top=(e.clientY?100*(e.clientY-rect.top)/rect.height:50)+'%'};$('fields').append(plot);return}
const ref=g.fields.find(f=>f.image);if(ref){const img=document.createElement('img');img.src=ref.image;img.alt=title(g.name)+' intake reference';img.referrerPolicy='no-referrer';img.onerror=()=>{img.remove();const p=document.createElement('p');p.textContent='Room reference is unavailable in this browser. You can still explore the selection fields.';$('reference').append(p)};$('reference').append(img)}
const sorted=[...g.fields].sort((a,b)=>Number(b.id.includes('inspiration'))-Number(a.id.includes('inspiration')));sorted.forEach(f=>$('fields').append(field(f)));if(g.name.includes('CONTRACTOR'))$('sectionNote').textContent='Try the contractor contact fields. This demo never sends contractor invitations or reminders.';if(g.name==='BEDROOMS')$('sectionNote').textContent='One bedroom example is shown. The customer intake repeats bedroom selections based on the project.';}
function move(i){index=i;render();$('title').focus();window.scrollTo({top:0,behavior:'smooth'})}
$('start').onclick=()=>{document.querySelector('.intro').hidden=true;$('walkthrough').hidden=false;move(0)};$('sectionPicker').onchange=e=>move(Number(e.target.value));$('back').onclick=()=>move(Math.max(0,index-1));$('next').onclick=()=>{if(index<groups.length-1)move(index+1);else{$('walkthrough').hidden=true;$('complete').hidden=false;window.scrollTo(0,0)}};$('restart').onclick=()=>{Object.keys(answers).forEach(k=>delete answers[k]);Object.keys(files).forEach(k=>delete files[k]);$('complete').hidden=true;$('walkthrough').hidden=false;move(0)};
})();
